project: python-tokai-37
version: 1
runtime: python27
module: default
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always
  
- url: /admin/.*
  script: admin.admin
  login: admin
  secure: always

- url: .*
  script: main.app
#  login: required
#  secure: always

libraries:
- name: flask
  version: 0.12